USE wellsy;

-- =========================================
-- 기존 테이블 삭제
-- =========================================

DROP TABLE IF EXISTS MEMBER_HEALTH_STANDARD;
DROP TABLE IF EXISTS ACCESS_LOG;
DROP TABLE IF EXISTS NOTICE_COMMENT;
DROP TABLE IF EXISTS NOTICE;
DROP TABLE IF EXISTS HEALTH_ALERT;
DROP TABLE IF EXISTS EXERCISE_PLAN;
DROP TABLE IF EXISTS AI_PLAN;
DROP TABLE IF EXISTS AI_CONSULTATION;
DROP TABLE IF EXISTS AI_CHAT_MESSAGE;
DROP TABLE IF EXISTS AI_CHAT_ROOM;
DROP TABLE IF EXISTS HEALTH_REPORT;
DROP TABLE IF EXISTS HEALTH_CHECKUP;
DROP TABLE IF EXISTS CHECKUP_RESERVATION;
DROP TABLE IF EXISTS MEAL_ITEM;
DROP TABLE IF EXISTS MEAL_RECORD;
DROP TABLE IF EXISTS SLEEP_RECORD;
DROP TABLE IF EXISTS EXERCISE_RECORD;
DROP TABLE IF EXISTS HEALTH_RECORD;
DROP TABLE IF EXISTS EXERCISE;
DROP TABLE IF EXISTS HEALTH_STANDARD;
DROP TABLE IF EXISTS SCHEDULE;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS JOB;
DROP TABLE IF EXISTS DEPARTMENT;

-- =========================================
-- 부서
-- =========================================

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INT NOT NULL PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100) NOT NULL
);





-- =========================================
-- 직급
-- =========================================

CREATE TABLE JOB (
    JOB_ID INT NOT NULL PRIMARY KEY,
    JOB_NAME VARCHAR(100) NOT NULL
);





-- =========================================
-- 사원
-- =========================================

CREATE TABLE EMPLOYEE (
    EMPLOYEE_NO INT NOT NULL PRIMARY KEY,
    LOGIN_ID VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(300) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(20),
    GENDER VARCHAR(10) CHECK (GENDER IN ('M', 'F')),
    BIRTH_DATE DATE,
    ROLE VARCHAR(20) NOT NULL,
    HIRE_DATE DATE DEFAULT (CURRENT_DATE),
    STATUS VARCHAR(20) NOT NULL DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
    RESIGN_DATE DATE,
    DEPARTMENT_ID INT,
    JOB_ID INT,

    FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (DEPARTMENT_ID),

    FOREIGN KEY (JOB_ID)
        REFERENCES JOB (JOB_ID)
);





-- =========================================
-- 건강 기록
-- =========================================

CREATE TABLE HEALTH_RECORD (
    HEALTH_RECORD_ID INT NOT NULL PRIMARY KEY,
    EMPLOYEE_NO INT NOT NULL,
    RECORD_DATE DATE NOT NULL,
    HEIGHT DECIMAL(5,2),
    WEIGHT DECIMAL(5,2),
    BMI DECIMAL(5,2),
    SYSTOLIC_BP INT,
    DIASTOLIC_BP INT,
    BLOOD_SUGAR DECIMAL(6,2),
    CAFFEINE_AMOUNT DECIMAL(6,2),
    SMOKING_COUNT INT,
    ALCOHOL_AMOUNT DECIMAL(6,2),

    FOREIGN KEY (EMPLOYEE_NO)
        REFERENCES EMPLOYEE (EMPLOYEE_NO)
);





-- =========================================
-- 운동 정보
-- =========================================

CREATE TABLE EXERCISE (
    EXERCISE_ID INT NOT NULL PRIMARY KEY,
    EXERCISE_NAME VARCHAR(100) NOT NULL,
    EXERCISE_TYPE VARCHAR(50),
    DESCRIPTION VARCHAR(1000),
    DIFFICULTY VARCHAR(20),
    CALORIES_PER_MINUTE DECIMAL(6,2),
    THUMBNAIL_IMAGE_URL VARCHAR(500),
    GUIDE_IMAGE_URL VARCHAR(500)
);





-- =========================================
-- 운동 기록
-- =========================================

CREATE TABLE EXERCISE_RECORD (
    EXERCISE_RECORD_ID INT NOT NULL PRIMARY KEY,
    EMPLOYEE_NO INT NOT NULL,
    EXERCISE_ID INT NOT NULL,
    EXERCISE_DATE DATE NOT NULL,
    DURATION INT,
    TARGET_DURATION INT,
    TARGET_COUNT INT,
    ACHIEVEMENT_RATE DECIMAL(5,2),
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('Y', 'N')),
    FAILURE_REASON VARCHAR(500),
    MEMO VARCHAR(1000),

    FOREIGN KEY (EMPLOYEE_NO)
        REFERENCES EMPLOYEE (EMPLOYEE_NO),

    FOREIGN KEY (EXERCISE_ID)
        REFERENCES EXERCISE (EXERCISE_ID)
);





-- =========================================
-- 수면 기록
-- =========================================

CREATE TABLE SLEEP_RECORD (
    SLEEP_RECORD_ID INT NOT NULL PRIMARY KEY,
    EMPLOYEE_NO INT NOT NULL,
    SLEEP_DATE DATE NOT NULL,
    SLEEP_START DATETIME,
    SLEEP_END DATETIME,
    SLEEP_QUALITY INT CHECK (SLEEP_QUALITY BETWEEN 1 AND 5),
    MEMO VARCHAR(1000),

    FOREIGN KEY (EMPLOYEE_NO)
        REFERENCES EMPLOYEE (EMPLOYEE_NO)
);





-- =========================================
-- 식단 기록
-- =========================================

CREATE TABLE MEAL_RECORD (
    MEAL_RECORD_ID INT NOT NULL PRIMARY KEY,
    EMPLOYEE_NO INT NOT NULL,
    MEAL_DATE DATE NOT NULL,
    MEAL_TYPE VARCHAR(20) NOT NULL CHECK (MEAL_TYPE IN ('아침', '점심', '저녁', '간식')),

    FOREIGN KEY (EMPLOYEE_NO)
        REFERENCES EMPLOYEE (EMPLOYEE_NO)
);

-- =========================================
-- 음식 기록
-- =========================================

CREATE TABLE MEAL_ITEM (
    MEAL_ITEM_ID INT NOT NULL PRIMARY KEY,
    MEAL_RECORD_ID INT NOT NULL,
    FOOD_NAME VARCHAR(100) NOT NULL,
    AMOUNT_DESCRIPTION VARCHAR(100),
    CALORIES DECIMAL(6,2),
    PROTEIN DECIMAL(6,2),
    CARBOHYDRATE DECIMAL(6,2),
    FAT DECIMAL(6,2),

    FOREIGN KEY (MEAL_RECORD_ID)
        REFERENCES MEAL_RECORD (MEAL_RECORD_ID)
);

-- =========================================
-- 건강검진 예약
-- =========================================

CREATE TABLE CHECKUP_RESERVATION (
    RESERVATION_ID INT NOT NULL PRIMARY KEY,
    EMPLOYEE_NO INT NOT NULL,
    RESERVATION_DATE DATE NOT NULL,
    RECENT_CHECKUP_DATE DATE,
    HOSPITAL_NAME VARCHAR(100),
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('Y', 'N', 'C')),
    MEMO VARCHAR(500),
    CREATED_AT TIMESTAMP NOT NULL,

    FOREIGN KEY (EMPLOYEE_NO)
        REFERENCES EMPLOYEE (EMPLOYEE_NO)
);





-- =========================================
-- 건강검진
-- =========================================

CREATE TABLE HEALTH_CHECKUP (
    CHECKUP_ID INT NOT NULL PRIMARY KEY,
    RESERVATION_ID INT NOT NULL,
    RESULT_GRADE VARCHAR(20),
    SYSTOLIC_BP INT,
    DIASTOLIC_BP INT,
    BLOOD_SUGAR DECIMAL(6,2),
    TOTAL_CHOLESTEROL DECIMAL(6,2),
    WEIGHT DECIMAL(5,2),
    HEIGHT DECIMAL(5,2),
    RESULT_DETAIL VARCHAR(4000),
    CREATED_AT TIMESTAMP NOT NULL,

    FOREIGN KEY (RESERVATION_ID)
        REFERENCES CHECKUP_RESERVATION (RESERVATION_ID)
);

-- =========================================
-- 건강 알림
-- =========================================

CREATE TABLE HEALTH_ALERT (
    ALERT_ID INT NOT NULL PRIMARY KEY,
    CHECKUP_ID INT NOT NULL,
    ALERT_TYPE VARCHAR(50) NOT NULL,
    SEVERITY VARCHAR(20) NOT NULL,
    MESSAGE VARCHAR(1000),
    IS_READ CHAR(1) NOT NULL CHECK (IS_READ IN ('Y', 'N')),
    CREATED_AT TIMESTAMP NOT NULL,

    FOREIGN KEY (CHECKUP_ID)
        REFERENCES HEALTH_CHECKUP (CHECKUP_ID)
);





-- =========================================
-- 건강 기준
-- =========================================

CREATE TABLE HEALTH_STANDARD (
    STANDARD_ID INT NOT NULL PRIMARY KEY,
    METRIC_TYPE VARCHAR(50) NOT NULL,
    GENDER VARCHAR(10),
    MIN_AGE INT,
    MAX_AGE INT,
    MIN_VALUE DECIMAL(8,2),
    MAX_VALUE DECIMAL(8,2),
    UNIT VARCHAR(20),
    GRADE VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(500)

);





-- =========================================
-- AI 헬스코치 채팅방
-- =========================================

CREATE TABLE AI_CHAT_ROOM (
    CHAT_ROOM_ID INT NOT NULL PRIMARY KEY,
    EMPLOYEE_NO INT NOT NULL,
    CONSULTATION_TYPE VARCHAR(30) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,

    FOREIGN KEY (EMPLOYEE_NO)
        REFERENCES EMPLOYEE (EMPLOYEE_NO)
);

-- =========================================
-- AI 채팅내역
-- =========================================

CREATE TABLE AI_CHAT_MESSAGE(
    CHAT_MESSAGE_ID INT NOT NULL PRIMARY KEY,
    CHAT_ROOM_ID INT NOT NULL,
    SENDER_TYPE VARCHAR(20) NOT NULL CHECK (SENDER_TYPE IN ('USER', 'AI')),
    MESSAGE_CONTENT TEXT NOT NULL,
    SENT_AT TIMESTAMP NOT NULL,

    FOREIGN KEY (CHAT_ROOM_ID)
        REFERENCES AI_CHAT_ROOM (CHAT_ROOM_ID)
);

-- ==========================================
-- AI 리포트
-- ==========================================
CREATE TABLE HEALTH_REPORT (
    REPORT_ID INT NOT NULL PRIMARY KEY,
    EMPLOYEE_NO INT NOT NULL,
    PERIOD_START_DATE DATE NOT NULL,
    PERIOD_END_DATE DATE NOT NULL,
    SLEEP_SCORE TINYINT,
    EXERCISE_SCORE TINYINT,
    TOTAL_SCORE TINYINT,
    REPORT_SUMMARY VARCHAR(1000),
    REPORT_CONTENT TEXT,
    PDF_FILE_URL VARCHAR(500),
    CREATED_AT TIMESTAMP NOT NULL,

    FOREIGN KEY (EMPLOYEE_NO)
        REFERENCES EMPLOYEE (EMPLOYEE_NO)
);





-- =========================================
-- 공지사항
-- =========================================

CREATE TABLE NOTICE (
    NOTICE_ID INT NOT NULL PRIMARY KEY,
    EMPLOYEE_NO INT NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(4000) NOT NULL,
    IS_PINNED INTEGER NOT NULL,
    VIEW_COUNT INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('Y', 'N')),
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME,

    FOREIGN KEY (EMPLOYEE_NO)
        REFERENCES EMPLOYEE (EMPLOYEE_NO)
);





-- =========================================
-- 공지사항 댓글
-- =========================================

CREATE TABLE NOTICE_COMMENT (
    COMMENT_ID INT NOT NULL PRIMARY KEY,
    NOTICE_ID INT NOT NULL,
    EMPLOYEE_NO INT NOT NULL,
    CONTENT VARCHAR(2000) NOT NULL,
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('Y', 'N')),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,

    FOREIGN KEY (NOTICE_ID)
        REFERENCES NOTICE (NOTICE_ID),

    FOREIGN KEY (EMPLOYEE_NO)
        REFERENCES EMPLOYEE (EMPLOYEE_NO)
);


-- =========================================
-- 일반 스케줄
-- =========================================

CREATE TABLE SCHEDULE (
    SCHEDULE_ID INT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_NO INT NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT VARCHAR(1000),
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,

    PRIMARY KEY (SCHEDULE_ID),
    CONSTRAINT FK_SCHEDULE_EMPLOYEE FOREIGN KEY (EMPLOYEE_NO) REFERENCES EMPLOYEE (EMPLOYEE_NO)
);