USE wellsy;

DROP TABLE MEMBER_HEALTH_STANDARD;
DROP TABLE ACCESS_LOG;
DROP TABLE NOTICE_COMMENT;
DROP TABLE NOTICE;
DROP TABLE HEALTH_ALERT;
DROP TABLE EXERCISE_PLAN;
DROP TABLE AI_PLAN;
DROP TABLE AI_CONSULTATION;
DROP TABLE CHECKUP_RESERVATION;
DROP TABLE HEALTH_STANDARD;
DROP TABLE HEALTH_CHECKUP;
DROP TABLE MEAL_RECORD;
DROP TABLE SLEEP_RECORD;
DROP TABLE EXERCISE_RECORD;
DROP TABLE EXERCISE;
DROP TABLE HEALTH_RECORD;
DROP TABLE MEMBER;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INT NOT NULL,
    DEPARTMENT_NAME VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE MEMBER (
    MEMBER_ID INT NOT NULL,
    LOGIN_ID VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(300) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(20),
    GENDER VARCHAR(10),
    BIRTH_DATE DATE,
    ROLE VARCHAR(20) NOT NULL,
    DEPARTMENT_ID INT,
    STATUS VARCHAR(20) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UK_MEMBER_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_MEMBER_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (DEPARTMENT_ID)
);

CREATE TABLE HEALTH_RECORD (
    HEALTH_RECORD_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    RECORD_DATE DATE NOT NULL,
    HEIGHT DECIMAL(5,2),
    WEIGHT DECIMAL(5,2),
    BMI DECIMAL(5,2),
    SYSTOLIC_BP INT,
    DIASTOLIC_BP INT,
    BLOOD_SUGAR DECIMAL(6,2),
    CAFFEINE_AMOUNT DECIMAL(6,2),
    SMOKING_COUNT INT,
    ALCOHOL_AMOUNT DECIMAL(6,2),
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    CONSTRAINT PK_HEALTH_RECORD PRIMARY KEY (HEALTH_RECORD_ID),
    CONSTRAINT FK_HEALTH_RECORD_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE EXERCISE (
    EXERCISE_ID INT NOT NULL,
    EXERCISE_NAME VARCHAR(100) NOT NULL,
    EXERCISE_TYPE VARCHAR(50),
    DESCRIPTION VARCHAR(1000),
    DIFFICULTY VARCHAR(20),
    CALORIES_PER_MINUTE DECIMAL(6,2),
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_EXERCISE PRIMARY KEY (EXERCISE_ID)
);

CREATE TABLE EXERCISE_RECORD (
    EXERCISE_RECORD_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    EXERCISE_ID INT NOT NULL,
    EXERCISE_DATE DATE NOT NULL,
    DURATION INT,
    ACHIEVEMENT_RATE DECIMAL(5,2),
    STATUS VARCHAR(20) NOT NULL,
    FAILURE_REASON VARCHAR(500),
    MEMO VARCHAR(1000),
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_EXERCISE_RECORD PRIMARY KEY (EXERCISE_RECORD_ID),
    CONSTRAINT FK_EXERCISE_RECORD_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_EXERCISE_RECORD_EXERCISE
        FOREIGN KEY (EXERCISE_ID)
        REFERENCES EXERCISE (EXERCISE_ID)
);

CREATE TABLE SLEEP_RECORD (
    SLEEP_RECORD_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    SLEEP_DATE DATE NOT NULL,
    SLEEP_START DATETIME,
    SLEEP_END DATETIME,
    SLEEP_DURATION DECIMAL(4,2),
    SLEEP_QUALITY INT,
    MEMO VARCHAR(1000),
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_SLEEP_RECORD PRIMARY KEY (SLEEP_RECORD_ID),
    CONSTRAINT FK_SLEEP_RECORD_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE MEAL_RECORD (
    MEAL_RECORD_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    MEAL_DATE DATE NOT NULL,
    MEAL_TYPE VARCHAR(20) NOT NULL,
    MEAL_CONTENT VARCHAR(2000),
    CALORIES DECIMAL(7,2),
    CARBOHYDRATE DECIMAL(7,2),
    PROTEIN DECIMAL(7,2),
    FAT DECIMAL(7,2),
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_MEAL_RECORD PRIMARY KEY (MEAL_RECORD_ID),
    CONSTRAINT FK_MEAL_RECORD_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE HEALTH_CHECKUP (
    CHECKUP_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    CHECKUP_DATE DATE NOT NULL,
    HOSPITAL_NAME VARCHAR(100),
    RESULT_GRADE VARCHAR(30),
    BLOOD_PRESSURE VARCHAR(30),
    BLOOD_SUGAR DECIMAL(6,2),
    TOTAL_CHOLESTEROL DECIMAL(6,2),
    WEIGHT DECIMAL(5,2),
    HEIGHT DECIMAL(5,2),
    RESULT_DETAIL VARCHAR(2000),
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_HEALTH_CHECKUP PRIMARY KEY (CHECKUP_ID),
    CONSTRAINT FK_HEALTH_CHECKUP_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE HEALTH_STANDARD (
    STANDARD_ID INT NOT NULL,
    METRIC_TYPE VARCHAR(50) NOT NULL,
    GENDER VARCHAR(10),
    MIN_AGE INT,
    MAX_AGE INT,
    MIN_VALUE DECIMAL(8,2),
    MAX_VALUE DECIMAL(8,2),
    GRADE VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(500),
    CONSTRAINT PK_HEALTH_STANDARD PRIMARY KEY (STANDARD_ID)
);

CREATE TABLE CHECKUP_RESERVATION (
    RESERVATION_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    RESERVATION_DATE DATE NOT NULL,
    LAST_CHECKUP_DATE DATE,
    HOSPITAL_NAME VARCHAR(100),
    STATUS VARCHAR(20) NOT NULL,
    MEMO VARCHAR(500),
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_CHECKUP_RESERVATION PRIMARY KEY (RESERVATION_ID),
    CONSTRAINT FK_CHECKUP_RESERVATION_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE AI_CONSULTATION (
    CONSULTATION_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    CONSULTATION_TYPE VARCHAR(30) NOT NULL,
    USER_INPUT VARCHAR(4000),
    AI_RESPONSE VARCHAR(4000),
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_AI_CONSULTATION PRIMARY KEY (CONSULTATION_ID),
    CONSTRAINT FK_AI_CONSULTATION_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE AI_PLAN (
    PLAN_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    CONSULTATION_ID INT,
    GOAL VARCHAR(200) NOT NULL,
    PLAN_TITLE VARCHAR(200) NOT NULL,
    PLAN_DESCRIPTION VARCHAR(4000),
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_AI_PLAN PRIMARY KEY (PLAN_ID),
    CONSTRAINT FK_AI_PLAN_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_AI_PLAN_CONSULTATION
        FOREIGN KEY (CONSULTATION_ID)
        REFERENCES AI_CONSULTATION (CONSULTATION_ID)
);

CREATE TABLE EXERCISE_PLAN (
    EXERCISE_PLAN_ID INT NOT NULL,
    PLAN_ID INT NOT NULL,
    EXERCISE_ID INT NOT NULL,
    SCHEDULED_DATE DATE NOT NULL,
    TARGET_DURATION INT,
    TARGET_COUNT INT,
    ACHIEVEMENT_RATE DECIMAL(5,2),
    STATUS VARCHAR(20) NOT NULL,
    FAILURE_REASON VARCHAR(1000),
    AI_FEEDBACK VARCHAR(4000),
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_EXERCISE_PLAN PRIMARY KEY (EXERCISE_PLAN_ID),
    CONSTRAINT FK_EXERCISE_PLAN_PLAN
        FOREIGN KEY (PLAN_ID)
        REFERENCES AI_PLAN (PLAN_ID),
    CONSTRAINT FK_EXERCISE_PLAN_EXERCISE
        FOREIGN KEY (EXERCISE_ID)
        REFERENCES EXERCISE (EXERCISE_ID)
);

CREATE TABLE HEALTH_ALERT (
    ALERT_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    ALERT_TYPE VARCHAR(50) NOT NULL,
    SEVERITY VARCHAR(20) NOT NULL,
    MESSAGE VARCHAR(1000),
    DETECTED_DATE DATE NOT NULL,
    IS_READ CHAR(1) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_HEALTH_ALERT PRIMARY KEY (ALERT_ID),
    CONSTRAINT FK_HEALTH_ALERT_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE NOTICE (
    NOTICE_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(4000) NOT NULL,
    IS_PINNED CHAR(1) NOT NULL,
    VIEW_COUNT INT NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    CONSTRAINT PK_NOTICE PRIMARY KEY (NOTICE_ID),
    CONSTRAINT FK_NOTICE_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE NOTICE_COMMENT (
    COMMENT_ID INT NOT NULL,
    NOTICE_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    CONTENT VARCHAR(2000) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME,
    CONSTRAINT PK_NOTICE_COMMENT PRIMARY KEY (COMMENT_ID),
    CONSTRAINT FK_NOTICE_COMMENT_NOTICE
        FOREIGN KEY (NOTICE_ID)
        REFERENCES NOTICE (NOTICE_ID),
    CONSTRAINT FK_NOTICE_COMMENT_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE ACCESS_LOG (
    ACCESS_LOG_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    TARGET_MEMBER_ID INT NOT NULL,
    ACCESS_TYPE VARCHAR(30) NOT NULL,
    TARGET_TYPE VARCHAR(50) NOT NULL,
    IP_ADDRESS VARCHAR(50),
    ACCESSED_AT DATETIME NOT NULL,
    CONSTRAINT PK_ACCESS_LOG PRIMARY KEY (ACCESS_LOG_ID),
    CONSTRAINT FK_ACCESS_LOG_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_ACCESS_LOG_TARGET_MEMBER
        FOREIGN KEY (TARGET_MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE MEMBER_HEALTH_STANDARD (
    MEMBER_STANDARD_ID INT NOT NULL,
    MEMBER_ID INT NOT NULL,
    STANDARD_ID INT NOT NULL,
    MEASURED_VALUE DECIMAL(8,2),
    GRADE VARCHAR(30),
    EVALUATED_DATE DATE NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    CONSTRAINT PK_MEMBER_HEALTH_STANDARD PRIMARY KEY (MEMBER_STANDARD_ID),
    CONSTRAINT FK_MEMBER_HEALTH_STANDARD_MEMBER
        FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_MEMBER_HEALTH_STANDARD_STANDARD
        FOREIGN KEY (STANDARD_ID)
        REFERENCES HEALTH_STANDARD (STANDARD_ID)
);
