#배포 테스트용 편집
name: Deploy React

on:
  push:
    branches: 
      - main_sub
      - jaeyoung

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: wellsy_frontend/package-lock.json

      - name: Install dependencies
        working-directory: wellsy_frontend
        run: npm ci

      - name: Build React
        working-directory: wellsy_frontend
        run: npm run build

      - name: Copy dist to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "wellsy_frontend/dist/*"
          target: "/home/ubuntu/react-upload/"
          strip_components: 2

      - name: Deploy React with Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            sudo rm -rf /var/www/html/*
            sudo cp -r /home/ubuntu/react-upload/. /var/www/html/
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
            rm -rf /home/ubuntu/react-upload/*
            sudo nginx -t
            sudo systemctl reload nginx